// public/Header.nav.tsx
"use client";

import { FormSearch } from "@/components/forms";
import { Icon } from "@/components/general";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { HeaderNavProps } from "./Header.interfaces";

export default function HeaderNav({
  responsivity,
  suggestion,
  payload,
}: HeaderNavProps) {
  const pathname = usePathname()?.replace("/", "");
  const [active, setActive] = useState<
    "dashboard" | "library" | "bookmarks" | "profile"
  >((pathname as "dashboard") ?? "dashboard");

  useEffect(() => {
    setActive(pathname as "dashboard");
  }, [pathname]);

  return (
    <>
      {responsivity == "desktop" ? (
        <FormSearch cachedBooks={suggestion} />
      ) : null}

      <nav
        className={`header__nav ${
          responsivity == "mobile" ? "mobile-only" : "desktop-only"
        }`}
      >
        <Link
          href={"/dashboard"}
          data-active={active == "dashboard" ? active : ""}
        >
          <Icon type="dashboard" />
          <Icon type="dashboard_yellow" />
        </Link>

        <Link href={"/library"} data-active={active == "library" ? active : ""}>
          <Icon type="book" />
          <Icon type="book_yellow" />
        </Link>

        {payload?.email !== "admin@email.com" && (
          <Link
            href={"/bookmarks"}
            data-active={active == "bookmarks" ? active : ""}
          >
            <Icon type="bookmark" />
            <Icon type="bookmark_yellow" />
          </Link>
        )}

        <Link href={"/profile"} data-active={active == "profile" ? active : ""}>
          <Icon type="profile" />
          <Icon type="profile_yellow" />
        </Link>
      </nav>
    </>
  );
}

// src/sections/layouts/Header/HeaderNav.vue
<script setup>
import { ref, computed } from 'vue'
import { IconComponent } from '@/components/general'
import { FormSearchComponent } from '@/components/forms'

const active = ref('')

const props = defineProps({
  responsivity: String,
  suggestion: Array,
  payload: String
})

const pathname = computed(function () {
  return window.location.pathname.replace('/', '')
})

active.value = pathname.value ?? 'dashboard'
</script>

<template>
  <FormSearchComponent v-if="props.responsivity === 'desktop'" :cached-books="suggestion" />
  <nav
    class="header__nav"
    :class="{
      'mobile-only': props.responsivity === 'mobile',
      'desktop-only': props.responsivity === 'desktop'
    }"
  >
    <RouterLink to="/dashboard" :data-active="active === 'dashboard' ? active : ''">
      <IconComponent type="dashboard" />
      <IconComponent type="dashboard_yellow" />
    </RouterLink>

    <RouterLink to="/library" :data-active="active === 'library' ? active : ''">
      <IconComponent type="book" />
      <IconComponent type="book_yellow" />
    </RouterLink>

    <RouterLink
      to="/bookmarks"
      v-if="payload?.email !== 'admin@email.com'"
      :data-active="active === 'bookmarks' ? active : ''"
    >
      <IconComponent type="bookmark" />
      <IconComponent type="bookmark_yellow" />
    </RouterLink>

    <RouterLink to="/profile" :data-active="active === 'profile' ? active : ''">
      <IconComponent type="profile" />
      <IconComponent type="profile_yellow" />
    </RouterLink>
  </nav>
</template>
